import { describe, expect, it } from 'vitest'
import { getSqrtRatioAtTick, mulDiv, tickTableFromRanges, v3Swap, type V3SwapPool } from '../src/services/uniswapV3Math.ts'
import { parseV3State, replayV3Pool, serializeV3State, type V3PoolEvent, type V3Accrual } from '../src/services/userRevenueV3.ts'

// The exact v3 replay: swaps generated by the pool's own arithmetic (v3Swap, exact
// in and exact out, crossing initialized ticks) are re-run from their logs alone;
// a position's booked fees must equal liquidity × Σ fee growth inside / 2^128 to
// the unit, and a Collect after a poke must match the replay exactly.

const Q128 = 1n << 128n
const VAULT = '0x' + 'aa'.repeat(20)
const OTHER = '0x' + 'bb'.repeat(20)
const ev = (block: number, kind: V3PoolEvent['kind'], over: Partial<V3PoolEvent> = {}): V3PoolEvent => ({
  block, event: 0, kind, owner: '', lower: 0, upper: 0, liquidity: 0n, tick: 0, amount0: 0n, amount1: 0n, sqrtPrice: 0n, aux0: 0n, aux1: 0n, ...over,
})

function scenario(feeProtocol: number) {
  const events: V3PoolEvent[] = [ev(1, 'init', { sqrtPrice: getSqrtRatioAtTick(0), tick: 0 })]
  if (feeProtocol) events.push(ev(1, 'fp', { aux0: BigInt(feeProtocol), aux1: BigInt(feeProtocol) }))
  const ranges = [{ owner: VAULT, lower: -6000, upper: 6000, L: 10n ** 18n }, { owner: OTHER, lower: 0, upper: 600, L: 3n * 10n ** 17n }]
  for (const r of ranges) events.push(ev(2, 'mint', { owner: r.owner, lower: r.lower, upper: r.upper, liquidity: r.L }))
  let pool: V3SwapPool = {
    sqrtPriceX96: getSqrtRatioAtTick(0), tick: 0, liquidity: ranges[0].L + ranges[1].L, fee: 3000, tickSpacing: 60,
    ticks: tickTableFromRanges(ranges.map(r => ({ tickLower: r.lower, tickUpper: r.upper, net: r.L }))), feeProtocol: feeProtocol | (feeProtocol << 4),
  }
  let block = 3
  const growth = [0n, 0n]
  const swaps: Array<[boolean, bigint]> = [
    [false, 10n ** 16n], [false, -(10n ** 16n)], [true, 3n * 10n ** 16n], [false, 7n * 10n ** 15n + 12_345n], [true, -(2n * 10n ** 15n) - 7n], [false, 5n * 10n ** 16n], [true, 9n * 10n ** 16n],
  ]
  for (const [zeroForOne, amount] of swaps) {
    const r = v3Swap(pool, zeroForOne, amount)
    growth[zeroForOne ? 0 : 1] += r.feeGrowthX128
    events.push(ev(block++, 'swap', { amount0: r.amount0, amount1: r.amount1, sqrtPrice: r.sqrtPriceX96, tick: r.tick, liquidity: r.liquidity }))
    pool = { ...pool, sqrtPriceX96: r.sqrtPriceX96, tick: r.tick, liquidity: r.liquidity }
  }
  return { events, ranges, growth, block }
}

describe('v3 exact per-position fee replay', () => {
  for (const fp of [0, 4]) {
    it(`re-runs exact-in and exact-out swaps from their logs alone, crossing ticks, with feeProtocol ${fp}`, () => {
      const { events, block } = scenario(fp)
      const accruals: V3Accrual[] = []
      const stats = replayV3Pool(events, 3000, 60, 0, () => 0n, a => accruals.push(a), () => {})
      expect(stats.swaps).toBe(7)
      expect(stats.swapStateMismatch).toBe(0)
      expect(stats.dustNegative).toBe(0)
      // A poke and a full collect of the wide position: the chain pays exactly what the replay credited.
      const wide = stats.positions.get(`${VAULT}|-6000|6000`)!
      const owed = wide.uncollected
      const more = replayV3Pool([...events,
        ev(block, 'burn', { owner: VAULT, lower: -6000, upper: 6000 }),
        ev(block, 'collect', { owner: VAULT, lower: -6000, upper: 6000, amount0: owed[0], amount1: owed[1] }),
      ], 3000, 60, 0, () => 0n, () => {}, () => {})
      expect(more.collects).toBe(1)
      expect(more.collectsExact).toBe(1)
      const after = more.positions.get(`${VAULT}|-6000|6000`)!
      expect(after.booked).toEqual(wide.booked)
      expect(after.collectedFees).toEqual(owed)
      expect(after.uncollected).toEqual([0n, 0n])
      // Booked per position is the sum of its accruals.
      const sum = (owner: string, side: 0 | 1) => accruals.filter(a => a.owner === owner && a.side === side).reduce((x, a) => x + a.amount, 0n)
      expect(sum(VAULT, 0)).toBe(wide.booked[0])
      expect(sum(VAULT, 1)).toBe(wide.booked[1])
    })
  }

  it('books a lone in-range position liquidity × Σ fee growth / 2^128 exactly (the pool\'s own growth)', () => {
    const L = 10n ** 18n
    const events: V3PoolEvent[] = [ev(1, 'init', { sqrtPrice: getSqrtRatioAtTick(0), tick: 0 }), ev(2, 'mint', { owner: VAULT, lower: -60_000, upper: 60_000, liquidity: L })]
    let pool: V3SwapPool = { sqrtPriceX96: getSqrtRatioAtTick(0), tick: 0, liquidity: L, fee: 3000, tickSpacing: 60, ticks: tickTableFromRanges([{ tickLower: -60_000, tickUpper: 60_000, net: L }]) }
    const growth = [0n, 0n]
    let b = 3
    for (const [z, a] of [[true, 10n ** 15n + 1n], [false, -(10n ** 15n)], [false, 33_333_333n], [true, -999n]] as Array<[boolean, bigint]>) {
      const r = v3Swap(pool, z, a)
      growth[z ? 0 : 1] += r.feeGrowthX128
      events.push(ev(b++, 'swap', { amount0: r.amount0, amount1: r.amount1, sqrtPrice: r.sqrtPriceX96, tick: r.tick, liquidity: r.liquidity }))
      pool = { ...pool, sqrtPriceX96: r.sqrtPriceX96, tick: r.tick, liquidity: r.liquidity }
    }
    const stats = replayV3Pool(events, 3000, 60, 0, () => 0n, () => {}, () => {})
    const p = stats.positions.get(`${VAULT}|-60000|60000`)!
    expect(p.booked).toEqual([mulDiv(growth[0], L, Q128), mulDiv(growth[1], L, Q128)])
  })

  it('takes a vault\'s fee as the cumulative floor of its fees since the last collect ÷ the fee in force', () => {
    const { events } = scenario(0)
    const accruals: V3Accrual[] = []
    const stats = replayV3Pool(events, 3000, 60, 0, owner => (owner === VAULT ? 255n : 0n), a => accruals.push(a), () => {})
    const wide = stats.positions.get(`${VAULT}|-6000|6000`)!
    const cut = (side: 0 | 1) => accruals.filter(a => a.owner === VAULT && a.side === side).reduce((x, a) => x + a.vaultCut, 0n)
    expect(cut(0)).toBe(wide.booked[0] / 255n)
    expect(cut(1)).toBe(wide.booked[1] / 255n)
    expect(accruals.filter(a => a.owner === OTHER).every(a => a.vaultCut === 0n)).toBe(true)
  })
})

describe('v3 replay checkpoint (the month anchor\'s pool state)', () => {
  it('replaying from a serialized mid-history state books exactly what the full replay books after it', () => {
    const { events, block } = scenario(4)
    const all = [...events, ev(block, 'burn', { owner: OTHER, lower: 0, upper: 600 }), ev(block + 1, 'collect', { owner: OTHER, lower: 0, upper: 600, amount0: 1n, amount1: 1n })]
    const cut = 5
    const full: V3Accrual[] = []
    replayV3Pool(all, 3000, 60, cut, () => 255n, a => full.push(a), () => {})
    const head = replayV3Pool(all.filter(e => e.block <= cut), 3000, 60, cut, () => 255n, () => {}, () => {})
    const state = parseV3State(serializeV3State(head.state!))
    expect(state).toEqual(head.state)
    const tail: V3Accrual[] = []
    const rest = replayV3Pool(all.filter(e => e.block > cut), 3000, 60, cut, () => 255n, a => tail.push(a), () => {}, state)
    expect(tail).toEqual(full)
    expect(full.length).toBeGreaterThan(0)
    expect(rest.swapStateMismatch).toBe(0)
    const whole = replayV3Pool(all, 3000, 60, 0, () => 255n, () => {}, () => {})
    expect(rest.state).toEqual(whole.state)
  })
})
