-- Regular views (depend on tables above).
CREATE VIEW IF NOT EXISTS price_data.ohlc_15min_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_15min WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_1d_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_1d WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_1h_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_1h WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_1m_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_1m WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_1w_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_1w WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_30min_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_30min WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_4h_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_4h WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.ohlc_5min_query AS SELECT asset_id, interval_start, argMinMerge(open_state) AS open, maxMerge(high_state) AS high, minMerge(low_state) AS low, argMaxMerge(close_state) AS close, sumMerge(volume_buy_state) AS volume_buy, sumMerge(volume_sell_state) AS volume_sell, sumMerge(volume_buy_state) + sumMerge(volume_sell_state) AS volume_total FROM price_data.ohlc_5min WHERE (asset_id = {asset_id:UInt32}) AND ((interval_start >= {start_time:DateTime}) AND (interval_start <= {end_time:DateTime})) GROUP BY asset_id, interval_start ORDER BY interval_start ASC;
CREATE VIEW IF NOT EXISTS price_data.price_at_block AS SELECT asset_id, block_height, round(usd_price, 8) AS usd_price FROM price_data.prices FINAL WHERE (asset_id = {asset_id:UInt32}) AND (block_height = {block_height:UInt32});
CREATE VIEW IF NOT EXISTS price_data.price_at_block_by_symbol AS SELECT asset_id, block_height, round(usd_price, 8) AS usd_price FROM price_data.prices FINAL WHERE (asset_id = (SELECT asset_id FROM price_data.assets FINAL WHERE symbol = {symbol:String} LIMIT 1)) AND (block_height = {block_height:UInt32});
CREATE VIEW IF NOT EXISTS price_data.price_at_timestamp AS WITH nearest_block AS (SELECT argMin(block_height, abs(toUnixTimestamp(block_timestamp) - toUnixTimestamp({target_timestamp:DateTime}))) AS block_height FROM price_data.blocks WHERE (block_timestamp >= ({target_timestamp:DateTime} - toIntervalHour(1))) AND (block_timestamp <= ({target_timestamp:DateTime} + toIntervalHour(1)))) SELECT asset_id, block_height, round(usd_price, 8) AS usd_price FROM price_data.prices FINAL WHERE (asset_id = {asset_id:UInt32}) AND (block_height = (SELECT block_height FROM nearest_block));
CREATE VIEW IF NOT EXISTS price_data.price_range AS WITH base AS (SELECT block_height, round(usd_price, 8) AS usd_price FROM price_data.prices FINAL WHERE (asset_id = {asset_id:UInt32}) AND ((block_height >= {start_block:UInt32}) AND (block_height <= {end_block:UInt32}))) SELECT block_height, usd_price FROM base ORDER BY block_height ASC WITH FILL FROM {start_block:UInt32} TO {end_block:UInt32} + 1 STEP 1 INTERPOLATE (`usd_price` AS usd_price);
