-- User-authored explorer state (profiles, sessions, tag libraries). Unlike every
-- other table, this data is NOT reproducible from raw chain data: it is written
-- only by the api service and must be preserved across projection rebuilds and
-- backed up (see ops/backup-user-tables.sh). Same idiom as account_tags:
-- ReplacingMergeTree(updated_at) upsert-by-key with a soft-delete tombstone.
CREATE TABLE IF NOT EXISTS price_data.user_profiles (account_id String, display_name String DEFAULT '', avatar_version UInt32 DEFAULT 0, deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY account_id SETTINGS index_granularity = 64;
CREATE TABLE IF NOT EXISTS price_data.user_avatars (account_id String, image String, deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY account_id SETTINGS index_granularity = 8;
CREATE TABLE IF NOT EXISTS price_data.user_sessions (token_hash String, account_id String, expires_at DateTime, last_seen DateTime DEFAULT now(), deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY token_hash SETTINGS index_granularity = 64;
CREATE TABLE IF NOT EXISTS price_data.user_libraries (library_id String, owner_account_id String, name String, note String DEFAULT '', visibility LowCardinality(String) DEFAULT 'private', is_personal UInt8 DEFAULT 0, deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY library_id SETTINGS index_granularity = 64;
CREATE TABLE IF NOT EXISTS price_data.user_tags (library_id String, tag_id String, name String, color String DEFAULT '', icon String DEFAULT '', note String DEFAULT '', deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY (library_id, tag_id) SETTINGS index_granularity = 64;
CREATE TABLE IF NOT EXISTS price_data.user_tag_members (library_id String, tag_id String, account_id String, deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY (library_id, tag_id, account_id) SETTINGS index_granularity = 256;
CREATE TABLE IF NOT EXISTS price_data.user_library_subscriptions (library_id String, account_id String, status LowCardinality(String), origin LowCardinality(String), deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY (library_id, account_id) SETTINGS index_granularity = 64;
CREATE TABLE IF NOT EXISTS price_data.user_library_order (account_id String, library_ids Array(String), deleted UInt8 DEFAULT 0, created_at DateTime DEFAULT now(), updated_at DateTime64(3) DEFAULT now64(3)) ENGINE = ReplacingMergeTree(updated_at) ORDER BY account_id SETTINGS index_granularity = 64;
